# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive
- cc
- tagcloud
- tag
- category
- yandex  
- badges

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
#google_analytics: G-RF47NNRE5G
#google_adSense: ca-pub-1885096025224905
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
